services:
  mysql-backup:
    image: "wgmac/mysql-backup:${VERSION}"
    container_name: "mysql-backup"
    environment:
      #mysql数据库服务器地址，可写IP，域名，默认：localhost
      - DBHOST=172.172.172.100
      #mysql数据库端口6
      - DBPORT=3306
      #mysql数据库用户名
      - DBUSER=root
      #mysql数据库密码
      - DBPASS=root
      #最多保留文件数目，默认: 30
      - SAVECOUNT=20
      #备份文件存储路径，默认: /opt/data
      - BKPATH=/opt/data
      #备份策略，crond表达式, 默认: 5 0,12 * * *
      - CRON=2 0,6,12,18 * * *
    volumes:
      #备份文件存储路径
      - ./data:/opt/data